# Generated by Django 4.0 on 2024-02-04 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_collection', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
        ),
    ]
