# Generated by Django 4.0 on 2024-03-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
                ('Installation_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateValveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gatevalve_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diameter_m', models.IntegerField()),
                ('Material', models.CharField(max_length=50)),
                ('Length_m', models.FloatField(default=0)),
                ('Flow_Rate', models.FloatField()),
                ('Installation_date', models.DateField(blank=True, null=True)),
                ('Condition', models.CharField(max_length=50)),
                ('Leakage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pipeline_files/')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Capacity', models.FloatField(default=0)),
                ('Usage', models.FloatField(default=0)),
                ('Condition', models.CharField(max_length=50, null=True)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='storage_unit_files/')),
            ],
        ),
        migrations.CreateModel(
            name='TubeWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Pump_Type', models.CharField(max_length=50, null=True)),
                ('Depth', models.FloatField(default=0)),
                ('Flow_Rate', models.FloatField(default=0)),
                ('Condition', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TubeWellFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tubewell_files/')),
            ],
        ),
    ]
