# Generated by Django 4.0 on 2024-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='Material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
