# Generated by Django 4.0 on 2024-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0002_geojsonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='attributes',
            field=models.JSONField(null=True),
        ),
    ]
