# Generated by Django 4.0 on 2024-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0002_alter_pipeline_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='Condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='Flow_Rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='Leakage',
            field=models.BooleanField(null=True),
        ),
    ]
