# Generated by Django 4.0 on 2024-02-04 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0003_geodata_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geometry_collection',
        ),
        migrations.AddField(
            model_name='geodata',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='geodata',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geodata',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
