# Generated by Django 4.0 on 2024-04-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('issue_type', models.CharField(blank=True, choices=[('LEAKAGE', 'Leakage Detected Point'), ('WATER_ISSUE', 'Water Supply Issue'), ('PIPE_INSTALLATION', 'Requested New Location for Pipe Installation')], max_length=20, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
